'use client'
import { usePortalFetch } from '@/lib/use-portal-fetch'
import { useCallback, useEffect, useState } from 'react'
type Requirement = {id?:string;name:string;description:string;section:string;acceptedFormats:string[];maxSizeMb:number;isGlobal:boolean}
const empty:Requirement={name:'',description:'',section:'supporting',acceptedFormats:['pdf','jpg','png'],maxSizeMb:4,isGlobal:true}
export default function DocumentManager(){
  const fetch = usePortalFetch()
  const [links,setLinks]=useState<Array<{programId:string;documentTypeId:string;isMandatory:boolean}>>([])
  const [rows,setRows]=useState<Requirement[]>([])
  const [programs,setPrograms]=useState<Array<{id:string;title:string}>>([])
  const [form,setForm]=useState<Requirement>(empty)
  const [program,setProgram]=useState('')
  const [mandatory,setMandatory]=useState(true)
  const [error,setError]=useState('')
  const [message,setMessage]=useState('')
  const [busy,setBusy]=useState(false)
  const load=useCallback(async()=>{try{const response=await fetch('/api/admin/document-types');const data=await response.json();if(!response.ok)throw new Error(data.error);setRows(data.documentTypes);setPrograms(data.programs);setLinks(data.programDocuments)}catch(err){setError(err instanceof Error?err.message:'Unable to load requirements')}},[fetch])
  useEffect(()=>{void load()},[load])
  return <section className="space-y-6"><div><h1 className="text-3xl font-bold text-navy">Document checklist</h1><p className="mt-3 text-text-secondary">Place documents in the right form section. Global documents are required for every applicant; opportunity-specific documents can be required or optional.</p></div>
  {error&&<p role="alert" className="text-danger">{error}</p>}{message&&<p role="status">{message}</p>}
  <form className="grid gap-4 rounded-xl border bg-white p-5 sm:grid-cols-2" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/admin/document-types',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,programId:program||undefined,isMandatory:mandatory})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage('Document requirement saved.');setForm(empty);setProgram('');setMandatory(true);await load()}catch(err){setError(err instanceof Error?err.message:'Could not save')}finally{setBusy(false)}}}>
    <label>Document name<input required minLength={2} maxLength={120} value={form.name} onChange={event=>setForm({...form,name:event.target.value})} className="mt-2 w-full"/></label>
    <label>Application section<select value={form.section} onChange={event=>setForm({...form,section:event.target.value})} className="mt-2 w-full">{[['personal','Personal / identity'],['academic','Academic'],['language','Language proficiency'],['admissions','Admissions tests (SAT, GRE…)'],['supporting','Other supporting documents']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label className="sm:col-span-2">Instructions<textarea maxLength={1000} value={form.description??''} onChange={event=>setForm({...form,description:event.target.value})} className="mt-2 w-full"/></label>
    <label>Maximum file size (MB)<input type="number" min={1} max={4} required value={form.maxSizeMb} onChange={event=>setForm({...form,maxSizeMb:Number(event.target.value)})} className="mt-2 w-full"/></label>
    <fieldset><legend>Accepted formats</legend><div className="mt-2 flex gap-4">{['pdf','jpg','png'].map(format=><label key={format}><input type="checkbox" checked={form.acceptedFormats.includes(format)} onChange={event=>setForm({...form,acceptedFormats:event.target.checked?[...form.acceptedFormats,format]:form.acceptedFormats.filter(item=>item!==format)})}/> {format.toUpperCase()}</label>)}</div></fieldset>
    <label className="flex gap-3"><input type="checkbox" checked={form.isGlobal} onChange={event=>setForm({...form,isGlobal:event.target.checked})}/> Required for every application</label>
    {!form.isGlobal&&<><label>Opportunity<select required value={program} onChange={event=>{setProgram(event.target.value);setMandatory(links.find(link=>link.documentTypeId===form.id && link.programId===event.target.value)?.isMandatory ?? true)}} className="mt-2 w-full"><option value="">Choose opportunity</option>{programs.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="flex gap-3"><input type="checkbox" checked={mandatory} onChange={event=>setMandatory(event.target.checked)}/> Mandatory for this opportunity</label></>}
    <p className="text-sm text-text-secondary sm:col-span-2">Editing a document name, instructions or section updates it for every opportunity using it. Selecting another opportunity adds an assignment; it does not remove existing assignments.</p><div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-gold p-3 font-semibold text-navy">{form.id?'Save requirement':'Add requirement'}</button>{form.id&&<button type="button" onClick={()=>{setForm(empty);setProgram('')}} className="underline">Cancel edit</button>}</div>
  </form><ul className="divide-y rounded-xl border bg-white">{rows.map(row=><li key={row.id} className="p-5"><strong>{row.name}</strong><p className="mt-1 text-sm">{row.description}</p><p className="mt-2 text-xs capitalize">{row.section} · {row.isGlobal?'Required for every application':'Opportunity-specific'} · Up to {row.maxSizeMb} MB</p><ul className="mt-3 space-y-1 text-sm">{links.filter(link=>link.documentTypeId===row.id).map(link=><li key={link.programId}>{programs.find(item=>item.id===link.programId)?.title || 'Opportunity'} · {row.isGlobal || link.isMandatory ? 'Required' : 'Optional'}</li>)}</ul><button onClick={()=>{setForm({id:row.id,name:row.name,section:row.section,isGlobal:row.isGlobal,maxSizeMb:row.maxSizeMb,acceptedFormats:row.acceptedFormats??['pdf','jpg','png'],description:row.description??''});const assignment=links.find(link=>link.documentTypeId===row.id);setProgram(assignment?.programId??'');setMandatory(assignment?.isMandatory??true);window.scrollTo({top:0,behavior:'smooth'})}} className="mt-3 text-sm underline">Edit document and placement</button></li>)}</ul></section>
}
