import Link from 'next/link'
import { policiesApproved } from '@/lib/legal'
export default function PrivacyPolicy() {
  return <main className="mx-auto max-w-3xl px-6 py-16 space-y-6"><Link href="/" className="underline">Back to Cyndy</Link><h1 className="font-heading text-4xl font-bold text-navy">Privacy policy</h1>
    {!policiesApproved() && <p role="status" className="rounded border border-amber-300 bg-amber-50 p-4">Draft for business review. Applications cannot be submitted until the policy and support contact are approved.</p>}
    <p>Cyndy Educational Pathways manages the personal information provided through this application portal. Contact us through our <Link href="/contact" className="underline">support page</Link> about your information or this policy.</p>
    <h2 className="text-xl font-semibold">Information and purpose</h2><p>We collect account details, contact information, education and experience, application choices, supporting documents and payment receipts to provide the application service you request. Only provide another person’s details when you have permission or another valid basis to do so. We also process security and operational records to protect accounts and investigate problems.</p>
    <h2 className="text-xl font-semibold">Access and service providers</h2><p>Authorized staff access information needed for their work. Our portal uses Clerk for authentication, Neon for database storage, Cloudflare R2 for documents, Upstash for security controls, and Vercel for hosting. If email notifications are enabled, Resend processes delivery. Providers may process data outside your country. We share application information with institutions as needed for the application service and your instructions.</p>
    <h2 className="text-xl font-semibold">Retention</h2><p>We review abandoned drafts after 90 days of inactivity and closed applications after 12 months. We delete documents and personal information that are no longer needed for the service, unless you request continued assistance or we need specific records for a legal obligation or unresolved dispute. Payment and accounting records may be retained separately where required by law. You may request earlier deletion; we will explain any information that must be retained.</p>
    <h2 className="text-xl font-semibold">Basis for processing</h2><p>We use information to provide the service you request, meet legal obligations and protect the security of the portal. Where consent is required, we will request it separately and explain how to withdraw it. If an applicant is under 18, a parent or legal guardian should contact us before creating an application.</p><h2 className="text-xl font-semibold">Your choices</h2><p>Contact us to request access, correction or deletion, or to raise a privacy concern. We may verify your identity and may need to retain information required by law or an unresolved matter. We aim to acknowledge requests within three business days and respond within the applicable legal time limit. For services operated in Nigeria, you may also raise concerns with the Nigeria Data Protection Commission at ndpc.gov.ng. You can sign out of the portal at any time. Essential authentication and security storage are used to keep the portal working.</p>
    <h2 className="text-xl font-semibold">Security</h2><p>Use a unique password and keep your account credentials private. Report suspected unauthorized access through our support contact. No online system can guarantee complete security.</p>
  </main>
}
