import Link from 'next/link'
import { policiesApproved } from '@/lib/legal'
export default function TermsOfService() {
  return <main className="mx-auto max-w-3xl px-6 py-16 space-y-6"><Link href="/" className="underline">Back to Cyndy</Link><h1 className="font-heading text-4xl font-bold text-navy">Terms of service</h1>
    {!policiesApproved() && <p role="status" className="rounded border border-amber-300 bg-amber-50 p-4">Draft for business review. These terms are not yet open for applicant acceptance.</p>}
    <p>Cyndy Educational Pathways provides application preparation and coordination services. Your agreed package defines the number of applications and the service fee. Institutions and authorities make their own admission, scholarship and visa decisions; using this service does not guarantee an outcome.</p>
    <h2 className="text-xl font-semibold">Your responsibilities</h2><p>Provide accurate information, use documents you are entitled to submit, and review your application before submission. Keep your account secure and respond to requests in time for relevant deadlines. Tell our team promptly when information changes.</p>
    <h2 className="text-xl font-semibold">Fees and receipts</h2><p>Confirm your package and fee with our team before paying. Upload your receipt through the portal. A receipt upload is not payment confirmation; the team verifies it before unlocking your application. Institutional, examination, visa and other third-party charges are separate unless expressly included in your agreement.</p>
    <h2 className="text-xl font-semibold">Cancellations and refunds</h2><p>You may cancel by contacting our support inbox with your application reference. Before work begins, unused service fees are refundable. After work begins, we will provide a breakdown of the work completed and assess a refund of the unused portion. Non-recoverable third-party fees are excluded where these were disclosed and authorized. We aim to acknowledge requests within three business days and communicate a decision within ten business days. Approved refunds are processed within fourteen business days, subject to payment-provider processing times. Your statutory consumer rights are unaffected.</p>
    <h2 className="text-xl font-semibold">Acceptable use</h2><p>Do not submit false or unlawful material, access another person’s application without permission, or interfere with the portal. We may restrict access when needed to investigate misuse or protect users.</p>
    <h2 className="text-xl font-semibold">Questions and disputes</h2><p>Contact our team through the <Link href="/contact" className="underline">support page</Link> with your application reference. These terms are governed by Nigerian law, subject to mandatory protections that apply to you. We will first try to resolve concerns directly; nothing in these terms limits your right to contact a competent regulator or court.</p>
  </main>
}
